### ISSUE TITLE
Add support for signal handling

### ISSUE THREAD

**Issue by hex007** [bitbank2/BB-CP#1]
Request to support signal handling. This would allow the application (launched during boot) to be cleanly closed if needed.

Currently applications exits and error message is printed
`DATECODE sigHandler: Unhandled signal 2, terminating`

**Comment by bitbank2** [comment]
Reasonable request - I'll add it and close this issue when it's ready.

**Comment by bitbank2** [comment]
Added and appears to work as it should. I added a ctrl-c handler; you can do a pull request to add others if you think they need to be added.

**Comment by hex007** [comment]
Thanks for this

**Comment by hex007** [comment]
Thanks for this
