### ISSUE TITLE
Use VFB for "headless" Opi0 and NanopiDuo?

### ISSUE THREAD

**Issue by PhatHub** [bitbank2/BB-CP#13]
Since Orange Pi Armbian (20.05? Kernel 5.4.x) has basically made TV-out's Framebuffer impossible to activate now, (also Notro's FBTFT is getting more difficult to work with because the DTB instructions are getting unwieldy, not to mention it's been "orphaned" in the mainline kernels) CVBS-only SBCs like OpiZero and NanoDuo are almost out of luck in using SPI LCDs.

However, if we compile our own customized kernels, could we activate the Virtual framebuffer (VFB) and use BB-CP from that frame buffer to the ili9341? The default resolution seems to be 640x480, and if I'm not mistaken BB-CP can reduce resolution from 640x480@16bpp?

I know this circumvents the Mali400 video processor in the h3/h2+, but it's better than nothing right now... unless someone knows of a recent distro that still maintains CVBS out?

**Comment by bitbank2** [comment]
I am not a fan of the whole idea of "scraping" the framebuffer and sending it out to an SPI display. I wrote this code mostly as an experiment for my buddy "moosepr" and his TinyPi project. I don't possess these boards any more, so I can't test this scenario. What I would recommend is to write code that natively talks to SPI LCDs. You can use my "smartgear free" project as a starting point. The display output is faster and doesn't have to deal with hacks like BB-CP.

https://github.com/bitbank2/sg_free

**Comment by PhatHub** [comment]
Thanks!
After I wrote this question, I've been looking for standalone arcade emulators to modify to spit out data directly to the LCD instead of the framebuffer. A bit convoluted right now because everything is getting sucked into the LibRetro API, so there's a lot of code I'll have to parse through to figure this out.

I'll check out smartgear ASAP! Ultimately I want to take on MAME or FBNeo eventually (I have plans for a tiny vertical-screen arcade machine) 
Thanks for sharing your projects!!!
