### ISSUE TITLE
Run at startup?

### ISSUE THREAD

**Issue by turtiustrek** [bitbank2/BB-CP#3]
Hi(again :P), i have manged to get the display working it was just a matter of recompiling :P  but now i am stuck at launching it at boot :( 
 
i added this at `/etc/rc.local`
` sudo /boot/disp/BB-CP-master/bbcp --spi_bus 0 --lcd_dc 18--lcd_rst 22  spi_freq 46000000 --flip`
it does show me whatever it is on the console but only that frame like once :P

**Comment by bumtras** [comment]
Try adding " &" at the end of the line.

**Comment by turtiustrek** [comment]
Hi thanks for the reply it still gets stuck but every time different point and i have have to run the code again each time. Infact when run normally (Terminal) 

this error comes up:`2018-02-26 13:55:24 sigHandler: Unhandled signal 21, terminating
`

**Comment by bitbank2** [comment]
The way it's currently written, it waits on getchar() to quit. You'll need to remove that code and put it in an infinite loop because background processes aren't allowed to read from STDIN (signal 21).

**Comment by turtiustrek** [comment]
Thanks for the answer ill just put a while loop there :P or a useless if statement thanks again ill respond back if anything goes wrong :D

**Comment by MohammadMubin** [comment]
Just added this amazing complex code to make the thing work on boot :P 
```
int minecraft = 11;
while (minecraft > 10){
}
```
Cheers :D it works 👍

**Comment by MohammadMubin** [comment]
Sigh, right when i thought it worked i rebooted the machine the display does not update after adding the ampersand in :(  help?

**Comment by hex007** [comment]
It doesn't work because you put an infinite loop there. Use `pause();` rather than the infinite loop. That should work. Busy looping is bad.
