### ISSUE TITLE
bbcp prints help when called with no parameters

### ISSUE THREAD

**Issue by hex007** [bitbank2/BB-CP#6]
Since all parameters are same as default for my setup, there is no need to pass parameters. BB-CP prints help and exits. 

Suggested solution would be to follow Linux standard and print help only with '-h' or '--help' options.

**Comment by bitbank2** [comment]
I appreciate your suggestion. I think it's likely that there will be at least one parameter needed (e.g. --background). For reducing confusion, I'm going to leave it the way it is.
