### ISSUE TITLE
LCD_ORIENTATION_LANDSCAPE ???

### ISSUE THREAD

**Issue by dglaude** [bitbank2/BB-CP#8]
BB-CP is using the undefined LCD_ORIENTATION_LANDSCAPE:
```
main.c: In function ‘InitDisplay’:
main.c:277:23: error: ‘LCD_ORIENTATION_LANDSCAPE’ undeclared (first use in this function)
  spilcdSetOrientation(LCD_ORIENTATION_LANDSCAPE);
                       ^~~~~~~~~~~~~~~~~~~~~~~~~

```
Where in spi_lcd only the following are defined:
```
spi_lcd.h:#define LCD_ORIENTATION_NATIVE 1
spi_lcd.h:#define LCD_ORIENTATION_ROTATED 2
```

**Comment by bitbank2** [comment]
Sorry, I'll update BB-CP. I changed the terminology to fit better with reality. I've been testing on an ILI9342 and it's native orientation is landscape.
